### ISSUE TITLE
Doesn't work! 

### ISSUE THREAD

**Issue by edesdan** [lite3/Unity-BitmapFontImporter#1]
I have followed the suggested steps but it doesn't work in unity 5.4 . I cannot set the font on my test object, even with the ones provided by the plugin. Am I missing something?

Thanks!

**Comment by litefeel** [comment]
@edesdan you must use UGUI [Text](https://docs.unity3d.com/ScriptReference/UI.Text.html)

**Comment by Rhuantavan** [comment]
It was working before, but now in unity 5.5.0f3 the fonts don't show up. It does convert them, but it doesn't appear on screen. Even the provided example fonts don't work.
