### ISSUE TITLE
URL did not work for Unity Package Manager (Unity 2018.4.1f1)

### ISSUE THREAD

**Issue by Josh-McMillan** [lite3/Unity-BitmapFontImporter#10]
Had to fumble a bit with the url, partially my fault due to mistyping, but also because the #UMP did not work. It came back with an error before the program could even open, continuing resulted in the package not downloading from repo.

**Did work** with this added to _manifest.json_ instead of following the README: 
"com.litefeel.bitmapfontimporter": "https://github.com/litefeel/Unity-BitmapFontImporter.git" 
(note that I did not use #UMP for the git url)

**Comment by litefeel** [comment]
@Josh-McMillan 
![image](https://user-images.githubusercontent.com/1288575/62417898-6bb2c500-b68e-11e9-9442-3c34d8da1aa4.png)

It can work normally.
No errors.
