### ISSUE TITLE
Can't use BestFit option.

### ISSUE THREAD

**Issue by tracer8** [lite3/Unity-BitmapFontImporter#12]
Hi,
Thank you for best BitMap font importer.
I'm using it right now, but have 1 issue, i can't use BestFit option of Text. It always keep only 1 size, and not resize text inside border rect of RectTransform like normal Unity UI Text.
So did i miss something or currently this plugin not support this feature?
Many thank!

**Comment by tracer8** [comment]
Sample about BestFit:
1. Same border rect, same option:
- Normal Arial Font show only inside border
- Bitmap font lost some part of text.
![bitmap-1](https://user-images.githubusercontent.com/15725821/75612226-33a42f80-5b54-11ea-918c-3815066fdd3e.PNG)

2. I must increase size of border rect of Bitmap Text to make it show all text.
![bitmap-2](https://user-images.githubusercontent.com/15725821/75612225-330b9900-5b54-11ea-8eb3-7e7b7c6c8326.PNG)

3. Option:
![bitmap-3](https://user-images.githubusercontent.com/15725821/75612222-31da6c00-5b54-11ea-87ba-8c287462e01b.PNG)

So how can i make Bitmap show exactly like Normal(Arial ) font?

**Comment by litefeel** [comment]
Hi.
BestFit is only supported for dynamic fonts.
You can try TextMeshPro, it's free.
https://docs.unity3d.com/Packages/com.unity.textmeshpro@2.1/manual/index.html
Thanks.
