### ISSUE TITLE
Can't modify Character Space.

### ISSUE THREAD

**Issue by tracer8** [lite3/Unity-BitmapFontImporter#13]
Hi,
I try to generate font from ShoeBox, then use ingame, but Character Space too wide, so i try all seting on FontSetting, but nothing change. I can't find any option to modify Character Space. Did BitmapFontImporter support this?

![bitmap-4](https://user-images.githubusercontent.com/15725821/75613271-458ad000-5b5e-11ea-9e1d-e1e01b6915b6.PNG)

**Comment by litefeel** [comment]
Hi. 
http://renderhjs.net/shoebox/bitmapFont.htm
please see it.
The key is video.
ShoeBox will export the .fnt and .png files, and then import them in unity. Now it's ok.
Thanks.

**Comment by tracer8** [comment]
Thank you!
