### ISSUE TITLE
Minus font size and m_Descent problem (for Bitmap Font Generator)

### ISSUE THREAD

**Issue by ganaware** [lite3/Unity-BitmapFontImporter#3]
I generated a bitmap font by [Bitmap Font Generator](http://www.angelcode.com/products/bmfont/), then imported it by BitmapFontImporter. But, there was someting wrong:
1. With the option "Match char height", Bitmap Font Generater wote a minus font size.
    But, BitmapFontImporter cannot handle the minus font size.
2. BitmapFontImporter didn't write the m_Descent property to a .fontsetting file.
    I think without the m_Descent, UnityEngine.UI.Text component cannnot align text to the bottom of the rect (UnityEngine.TextAnchor.Lower*).

So, I wrote [a patch](https://gist.github.com/ganaware/a39f5c21f04203b92b6cbf834369de89) to fix those problems.

I tested it on Unity 5.4.4p1 for Windows 64bit.

**Comment by litefeel** [comment]
Fixed it in v1.5
