### ISSUE TITLE
Invalid file format when using TextMesh Pro Font Asset Creator

### ISSUE THREAD

**Issue by Celsyum** [lite3/Unity-BitmapFontImporter#8]
imported my png and fnt files , which are working good with any other tools outside Unity.
Generated .fontsetting file works good with Canvas/Ui/Text , but to work with TextMesh Pro I try to generate Font Atlas with "Font Asset Creator" and get error:

`
Font Asset Creator - Error Code [Invalid_File_Format] has occurred trying to load the [Arial] font file. This typically results from the use of an incompatible or corrupted font file.
UnityEngine.Debug:Log(Object)
TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow:DrawControls() (at Library/PackageCache/com.unity.textmeshpro@2.0.0/Scripts/Editor/TMPro_FontAssetCreatorWindow.cs:669)
TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow:OnGUI() (at Library/PackageCache/com.unity.textmeshpro@2.0.0/Scripts/Editor/TMPro_FontAssetCreatorWindow.cs:257)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`
 Any ideas what is causing this ?

**Comment by litefeel** [comment]
Hi.
TextMesh Pro doesn't support custom font.
So you can use the `.ttf ` font.

But I can convert bitmap fonts to TMP Sprites.
I will to do this on weekend.

**Comment by litefeel** [comment]
Sorry, I am not going to convert bitmapfont to TMP sprite, because the usage of sprites is inconsistent with the usage of plain text.

**Comment by Celsyum** [comment]
thank you for feedback, 
  luckily I found my old `.ttf` CUSTOM fonts and spent all night generating font settings with "Font Asset Creator". 
 So if I don't have original `.ttf` files and only Bitmap fonts (`.png` and `.fnt` or other data file) - i can not use BitmapFontImporter or any other available tool to prepare my bitmap font for TextMesh Pro ? (Please don't bother to look for answer if you don't know).
