### ISSUE TITLE
Feature Request: Support font outlines

### ISSUE THREAD

**Issue by LittleCodingFox** [lite3/Unity-BitmapFontImporter#9]
I tried to import a BMFont font with outlines and it didn't display correctly (displayed all garbled). I'm on Unity 2019.1. Would be awesome if this supported that.

**Comment by litefeel** [comment]
Hi. thanks for your feedback.
Can you submit the fnt file and texture?
Thanks.

**Comment by LittleCodingFox** [comment]
It seems my BMFont is acting strangely, now it won't even export the font. Keeps crashing. Maybe it wasn't working due to a glitch in exporting. Sorry for the trouble.
